services:
  voice-backend:
    container_name: voice_backend_app
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../api/src:/app
    env_file:
      - ../.env

    restart: unless-stopped

